<?php
$this->title = "My Albums";
$this->headTitle($this->title);
$new_album_url = $this->url(array('controller'=>'index',
			      'action' => 'add'));
?>

<p><a id="new" href="<?php echo $new_album_url; ?>">Add new album</a></p>
<table>
  <tr>
  <th width=200>Title</th> <th width=225>Artist</th> <tr>&nbsp;</th>
  </tr>
<?php 
foreach($this->albums as $album) {?>
<tr>
  <td width=200><?php echo $this->escape($album['title']); ?></td>
  <td width=225><span style="color:#33cc33;">
  <?php echo $this->escape($album['artist']); ?></span></td>
  <td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'edit', 'id' => $album['id']));?>">Edit</a>
  <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'delete', 'id' => $album['id']));?>">Delete</a></td>
</tr>
  <?php } ?>
</table>