
<?php
//$this->title = "Create Lab";
$this->headTitle($this->title);
?>

<div style="margin: 10px auto;width:800px;">
  <center><h1 style="margin-bottom:10px;"><?php echo $this->title; ?></h1></center>
  <div style="margin:15px 0;">
  <?php echo $this->outlines; ?>
  </div>
</div>
<div style="margin: auto;margin-left:200px;padding:20px 30px;font-size: 1.3em;width:500px;">
  Create a new lab. Labs are identified by their lab numbers, which must be unique.
</div>
