<!--?php echo $this->layout()->content; ? -->

<?php
$this->headMeta()->appendEttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Albums Galore');

echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
</head>
<body>
<div id="content">
  <h1><?php echo $this->escape($this->title); ?></h1>
<?php exho $this->layout()->content; ?>
</div>
</body>
</html>