<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8" />
<!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <![endif]-->

<title>Albums Galore</title>
<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/styles.css'; ?>" />
</head>

<body>
<div id="content" style="margin-left:10px;">
  <h1><?php echo $this->escape($this->title); ?></h1>
<?php echo $this->layout()->content; ?>
</div>
</body>
</html> 
