<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8" />
    <!--[if IE]>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <![endif]-->
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <title></title>
    <script>
      /*$(function() {
      $( "input[type=submit], button" )
      .button()
      .click(function( event ) {
      event.preventDefault();
      });
      });*/
    </script>
  </head>
  

  <body style="width:1200px;">
    <script type="text/javascript">
      var changed = false;
    </script>
    <?php echo $this->header; ?>
    <div id="content" style="margin: 20px 0 0 10px;">
   <?php if ($this->flash != '') { ?>
     <div id="flash"
          style="float:right;font-size:16px;border:1px solid #c00;background:#ffe;padding: 6px 10px;">
      <?php echo $this->flash; ?></div>
        <?php } ?>
      <div id="outer" style="margin-left: 10px;">
        <div id="wrapper"style="overflow:auto;" >
          <div id="pane"
               style="height: 600px; float: left;">
            <div style="margin: 0 0 0 100px; margin: 15px 0;" >
              <form method="post" action=""
                    enctype="application/x-www-form-urlencoded" name="doit"
                    id="doit">
                <?php echo $this->layout()->content; ?>
   <?php //echo $this->outlines;
                      echo $this->hidden; ?>
                <input type="hidden" name="action">
              </form>
            </div>
            <div style="height: 65px;">&nbsp;</div>
            <div style="clear: both;"></div>
          </div><!-- pane -->
        </div> <!-- wrapper -->
        <div style="clear:both;"></div>
      </div><!-- outer -->
    </div><!-- content -->
    <div id="footer"></div>
    <script>
$(function() {
  resetSize();
  $('#flash').delay(4000).fadeOut(1000);
  $(window).resize(function(){
    resetSize();
  });
});
    </script>    
  </body>
</html>
