<!DOCTYPE HTML>
<html>
 <head>
    <meta charset="utf-8" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <![endif]-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/styles.css'; ?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/dtree.css'; ?>" />
    <!--script type="text/javascript"
            src="<?php echo $this->baseUrl () . '/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl () . '/charisma/js/jquery-1.7.2.min.js'; ?>" / -->
    </script>
    <!-- link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/calendar.css'; ?>" />
    <script type="text/javascript" src="<?php echo $this->baseUrl() . '/js/calendar.js'; ?>" ></script-->
    <script type="text/javascript" src="<?php echo $this->baseUrl(). '/js/dtree.js'; ?>"></script>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl(). '/js/helpers.js'?>"></script>
    <title>The Title</title>
    <script>
  /*$(function() {
  $( "input[type=submit], button" )
  .button()
  .click(function( event ) {
  event.preventDefault();
  });
  });*/
   </script>
  </head>


<body style="width:1200px;">

<?php echo $this->header; ?>
<div id="content" style="margin-left:10px;width:100%;">
	  <?php echo $this->layout()->content; ?>
</div>

<div id="footer">
</div>


</body>
</html>
