<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <![endif]-->
    
    <title>ALl my pages</title>
    <link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/styles.css'; ?>" />
  </head>
  
  <body>
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
  </body>
</html> 
