<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8" />
    <!--[if IE]>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <![endif]-->
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <title>The Title</title>
    <script>
  /*$(function() {
  $( "input[type=submit], button" )
  .button()
  .click(function( event ) {
  event.preventDefault();
  });
  });*/ 
   </script>
  </head>

  <body style="width: 1200px;">
    <script type="text/javascript">
      var changed = false;
      var oldloc = <?php echo $this->thispage; ?>;
    </script>
    <?php echo $this->header; ?>
    <div id="content" style="margin-left: 10px;">
      <div id="content" style="margin: 20px 0 0 10px;">
         <?php if ($this->flash != '') { ?>
           <div id="flash"
            style="float:right;font-size:16px;border:1px solid #c00;background:#ffe;padding: 6px 10px;">
         <?php echo $this->flash; ?></div>
         <?php } ?>
      <h1><?php echo $this->escape($this->title); ?></h1>
      <?php echo $this->layout()->content; ?>

      <div id="outer" style="margin-left: 10px;">
        <div id="wrapper" >
          <div id="leftpane"
               style="width: 200px; min-height: 500px; border-right: none; background-color: #fffff0; float: left;">
            <script type="text/javascript">d = new dTree('d'); <?php echo $this->treelines; ?> document.write(d);</script>
          </div>
          <div id="rightpane"
             style="height: 600px; float:left;" >
            <div style="margin: 0 10px; margin-bottom: 15px;" >
              <form method="post" action=""
                    enctype="application/x-www-form-urlencoded" name="slipta"
                    id="slipta">
                <?php echo $this->outlines; echo $this->hidden; ?>
                <input type="hidden" name="action">
                <!--input type="hidden" name="thispage" value="<?php echo $this->thispage; ?>"-->
                <?php echo $this->buttons; ?>
              </form>
            </div>
            <div style="height: 65px;">&nbsp;</div>
            <div style="clear: both;"></div>
          </div><!-- rightpane -->
        </div> <!-- wrapper -->
        <div style="clear:both;"></div>
      </div><!-- outer -->
	  </div><!-- content -->
	  <div id="footer"></div>
	 
    <script>
$(function() {
resetSize2();
$(window).resize(function(){
    resetSize2();
  });
});
    </script>
  </body>
</html>
