
<?php
$this->title = "Login";
$this->headTitle($this->title);
// setting up the dialog
$_fields = array (
    'username',
    'password',
    'submit'
);
$flist = array (
    '_fields' => $_fields,
    'username' => array (
        'type' => 'string',
        'length' => 32,
        'label' => 'Email Address:'
    ),
    'password' => array (
        'type' => 'password',
        'length' => 32,
        'label' => 'Password:'
    ),
    'submit' => array (
        'type' => 'submit',
        'value' => 'Login'
    )
);
// logit("flist: {$flist}");
$outlines = dumpForm ( $flist, $this->langtag );
$this->formtext = $outlines;
?>

<div style="margin: 10px auto;width:800px;">
  <center><h1 style="margin-bottom:10px;"><?php echo $this->title; ?></h1></center>
  <div style="margin:15px 0;">
  <?php echo $this->formtext; ?>
  </div>
</div>
<div style="margin: auto;padding:20px 30px;font-size: 1.3em;width:400px;">
  Login here to get access to Audits.
  The following type of audits can be worked on here:
  <ul>
    <li>SLIPTA</li>
    <li>BIosafety</li>
    <li>TB</li>
  </ul>
</div>
